version: "3.8"

services:
  # Frontend services
  frontend1:
    image: agustinvera/mortgageloan-frontend:latest
    networks:
      - frontend-network

  frontend2:
    image: agustinvera/mortgageloan-frontend:latest
    networks:
      - frontend-network

  frontend3:
    image: agustinvera/mortgageloan-frontend:latest
    networks:
      - frontend-network

  # Backend services
  backend1:
    image: agustinvera/mortgageloan-backend:latest
    environment:
      - DB_HOST=postgres-container
    networks:
      - backend-network

  backend2:
    image: agustinvera/mortgageloan-backend:latest
    environment:
      - DB_HOST=postgres-container
    networks:
      - backend-network

  backend3:
    image: agustinvera/mortgageloan-backend:latest
    environment:
      - DB_HOST=postgres-container
    networks:
      - backend-network

  # PostgreSQL Service
  postgres-container:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Admin
      - POSTGRES_DB=dbmortgageloan
    volumes:
      - tingeso-volume:/var/lib/postgresql/data
    networks:
      - backend-network

  # Nginx for frontend load balancing
  nginx-frontend:
    image: nginx:latest
    ports:
      - "8070:80"
    volumes:
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend-network

  # Nginx for backend load balancing
  nginx-backend:
    image: nginx:latest
    ports:
      - "8090:8090"
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network:

volumes:
  tingeso-volume:
